# Generated by Django 3.2.10 on 2022-01-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('type', models.CharField(max_length=15, null=True)),
                ('source', models.CharField(max_length=15, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('by', models.CharField(blank=True, max_length=64, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('kids', models.IntegerField(blank=True, null=True)),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
                ('top', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='story', editable=False, max_length=15)),
                ('source', models.CharField(default='new', editable=False, max_length=15, null=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('by', models.CharField(default='auth user', editable=False, max_length=200)),
                ('url', models.URLField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
