# Generated by Django 3.2.10 on 2021-12-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='date_fetched',
            new_name='time',
        ),
    ]
